#ifndef VIRT_OBJECT_H
#define VIRT_OBJECT_H

#include <functional>
#include <algorithm>
#include <format>

#include "demangle.h"
#include "cpp_backtrace.h"

namespace virt_object {

template <typename T>
using ref_t = std::shared_ptr<T>;

using ret_t = int64_t;

template <typename Id>
struct object_t : public std::enable_shared_from_this<object_t<Id>> {
private:
    struct Private{ explicit Private() = default; };

public:
    object_t() {}
    virtual ~object_t() { uninit(); }

    /* you must use some value generated by compile_unique_id for this one */
    virtual Id type_id() const = 0;
    virtual std::string to_string() const = 0;

    virtual ret_t init() { return 0; };
    virtual ret_t uninit() { return 0; };

    auto shared_this() { return std::enable_shared_from_this<object_t<Id>>::shared_from_this(); }

    template <typename T>
    ref_t<T> to_related() {
        auto ret = std::dynamic_pointer_cast<T>(shared_this());
        if (!ret)
            throw std::runtime_error{
                    std::format("Tried to build a reference of invalid type {} to {}",
                    demangle(typeid(this).name()), demangle<T>())};
        return ret;
    }

    template <class T, class... Args>
    friend constexpr std::shared_ptr<T> std::make_shared(Args&&... args);

    std::shared_ptr<void> usr_ptr;
};

/*!
 * Compile Time Unique ID
 * 
 * This insanity needs some sort of explanation.
 *
 * Origin of the code:
 *   https://stackoverflow.com/a/74453799/7107236
 * The original idea comes from Filip Roséen:
 *   https://refp.se/articles/constexpr-counter
 *
 * In my own words and understanding:
 *
 *   - The core of this code is the function `is_defined`. Initially, it is *not*
 *     defined in the context of the templated `exists`, so the call to
 *     `is_defined(Tag{})` fails SFINAE and selects the second `exists` overload.
 *
 *   - That second overload returns `false`, but it also explicitly instantiates
 *     `generator`. Instantiating `generator` defines `is_defined` for the
 *     respective number. Therefore, the next time `exists` is queried for the
 *     same Id, `is_defined` *is* defined.
 *
 * This code raises `-Wnon-template-friend` (as you would've guessed already) and
 * may become unusable in the future. I hope not.
 */
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wnon-template-friend"
#endif
template<typename UniqueTag, auto Id>
struct compile_counter {
    using tag = compile_counter;

    struct generator { friend consteval auto is_defined(tag) { return true; } };
    friend consteval auto is_defined(tag);

    struct generator_max { friend consteval auto is_max(tag) { return true; } };
    friend consteval auto is_max(tag);

    template<typename Tag = tag, auto = is_defined(Tag{}), auto = is_max(Tag{})>
    static consteval auto exists(auto) { throw "Unique id was called after max queried;"; };

    template<typename Tag = tag, auto = is_defined(Tag{})>
    static consteval auto exists(auto) { return true; }

    static consteval auto exists(...) { return generator(), false; }


    template<typename Tag = tag, auto = is_defined(Tag{})>
    static consteval auto exists_max(auto) { return generator_max(), true; }

    static consteval auto exists_max(...) { return false; }
};

template<typename UniqueTag, auto Id = int{}, typename = decltype([]{})>
consteval auto compile_max_id() {
    if constexpr (not compile_counter<UniqueTag, Id>::exists_max(Id))
        return Id - 1;
    else
        return compile_max_id<UniqueTag, Id + 1>();
}
template<typename UniqueTag, auto Id = int{}, typename = decltype([]{})>
consteval auto compile_unique_id() {
    if constexpr (not compile_counter<UniqueTag, Id>::exists(Id))
        return Id;
    else
        return compile_unique_id<UniqueTag, Id + 1>();
}
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif

/* Example for the above example, you can use whatever type as a tag */
struct compile_counter_example_tag_t;
static_assert(compile_unique_id<compile_counter_example_tag_t>() == 0);
static_assert(compile_unique_id<compile_counter_example_tag_t>() == 1);
static_assert(compile_unique_id<compile_counter_example_tag_t>() == 2);
static_assert(compile_unique_id<compile_counter_example_tag_t>() == 3);

/* modification of https://stackoverflow.com/a/61922662/3727118 */
template <typename Tag>
class EnumClass {
  private:
    int value_;
    const char *str_;
  public:
    explicit constexpr EnumClass(int value, const char *str = "UNNAMED_ENUM")
    : value_(value), str_(str) {}

    constexpr EnumClass() = default;
    ~EnumClass() = default;
    constexpr EnumClass(const EnumClass &) = default;
    constexpr EnumClass &operator=(const EnumClass &) = default;

    constexpr operator int() const {return    value_;}
    constexpr int value() const {return value_;}
    constexpr const char *name() const {return str_;}
};

} /* virt_object */


#endif
